server:
    port: ${APP_SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: managerCreation
          uri: ${APP_URL_MANAGER_CREATION:http://localhost:8081/}
          predicates:
            - Path=/v1/api/creation/**